= Catalog Service
ifndef::imagesdir[:imagesdir: images]

== 學習目標

* 使用Spring Data訪問MongoDB
* 使用Spring Data REST從Repository構建REST風格web services
* 使用Spring Test/MockMVC測試REST風格web services
* 使用Spring REST Docs生成簡潔、準確且結構良好的web services API文檔

== 設計

[plantuml,catalog-design,png]
....
@startuml
package "Catalog Service" {
    REST - [Repository]
}

database MongoDB

[Repository] --> MongoDB
@enduml
....

Catalog service以REST風格的API向外提供服務，數據全部存儲在MongoDB中，數據訪問層以Repository模式構建。

== 業務模型

Catalog service維護兩個業務模型，Product和ProductImage。

[plantuml, catalog-model, png]
....
@startuml
class Product <<Entity>> {
    -id: String
    -title: String
    -tags: List<String>
    -images: List<ProductImage>
    -createdAt: Date
    -updatedAt: Date
}

class ProductImage <<Entity>> {
    -id: String
    -src: String
    -createdAt: Date
    -updatedAt: Date
}

Product "0..1" *- "1..*" ProductImage: images
@enduml
....

== REST API

=== Product

|===
|操作|URL|HTTP Method

|創建新Product
|/products
|POST

|更新Product
|/products/<productId>
|PUT

|更新與ProductImage之間的關聯
|/products/<productId>/images
|PUT

|移除Product
|/products/<productId>
|DELETE

|讀取單個Product
|/products/<productId>
|GET

|分頁讀取所有Product
|/products?page=<pageIndex>&size=<pageSize>
|GET

|讀取Product關聯的ProductImage
|/products/<productId>/images
|GET
|===

=== ProductImage

|===
|操作|URL|HTTP Method

|創建新ProductImage
|/productImages
|POST

|更新ProductImage
|/productImages/<productImageId>
|PUT

|移除ProductImage
|/productImages/<productImageId>
|DELETE

|讀取單個ProductImage
|/productImages/<productImageId>
|GET

|分頁讀取所有ProductImage
|/productImages?page=<pageIndex>&size=<pageSize>
|GET
|===

== 實現

=== 業務模型

==== Product

.Product.java
[source,java]
----
@Getter <1>
@Setter <2>
@Document <3>
public class Product {

  @Id <4>
  private String id;
  private String title;
  private List<String> tags;
  @DBRef <5>
  private List<ProductImage> images;
  private Date createdAt;
  private Date updatedAt;
}
----

利用Lombok編譯期生成getter/setter方法，減少重復的模板代碼。

使用Spring Data MongoDB提供的注解描述java類與MongoDB集合、java字段與MongoDB字段之間的映射關系。Spring Data MongoDB會根據映射關系生成對應的Repository實現。

. @Getter `lombok.Getter` 在編譯期為所有字段生成Getter訪問器。比如針對字段`private String id`，其生成了相當與以下源代碼的Getter訪問器：
+
[source,java]
----
public String getId() {
    return this.id;
}
----

. @Setter `lombok.Setter` 在編譯期為所有字段生成Setter訪問器。比如針對字段`private String id`，其生成了相當與以下代碼的Setter訪問器：
+
[source,java]
....
public void setId(String id) {
    this.id = id;
}
....

. @Document `org.springframework.data.mongodb.core.mapping.Document` @Document 將一個Java類映射到MongoDB的某個Collection。在MongoDB中，Collection是Document的集合。在Java中，Class是Object的模板，"從某個Class實例出來的Object"是一個Object的集合。所以，在Java Class/Object與MongoDB Collection/Document映射關系中，Class對應Collection，Object對應Document。而Object中的字段對應Document中的字段。
+
[plantuml]
....
digraph d {
    rankdir=LR
    l [shape=record, label="<a>@Document\lpublic class Product \{\l|<b>  @Id\l  private String id;\l|<c>  private String title;\l|<d>  private List\<String\> tags;\l|<e>  @DBRef\l  private List\<ProductImage\> images;|<f>  private Date createdAt;\l|<g>  private Date updatedAt;\l|\}\l"]

    m [shape=record, label="<a>object product:Product \{\l|<b>id = \"5db3a5385cb95ce6e56a9248\"\l|<c>title = \"iMac\"\l|<d>tags = [\"mac\", \"apple\"]\l|<e>images = [objectA, objectB]\l|<f>createdAt = 2019-10-26T01:45:28.703Z\l|<g>updatedAt = 2019-11-03T09:31:00.103Z\l|\}\l"]

    r [shape=record, label="<a>\{\l|<b>	\"_id\" : ObjectId(\"5db3a5385cb95ce6e56a9248\"),\l|<c>	\"title\" : \"iMac\",\l|<d>	\"tags\" : [\l		\"mac\",\l		\"apple\"\l	],\l|<e>	\"images\" : [\l		DBRef(\"productImage\", ObjectId(\"5dabf9ab5cb95c4dad891a95\")),\l		DBRef(\"productImage\", ObjectId(\"5dabf9a05cb95c4dad891a94\")),\l	],\l|<f>	\"createdAt\" : ISODate(\"2019-10-26T01:45:28.703Z\"),\l|<g>	\"updatedAt\" : ISODate(\"2019-11-03T09:31:00.103Z\"),\l|	\"_class\" : \"io.github.rscai.microservices.catalog.model.Product\"\l\}\l"]

    l:b -> m:b -> r:b
    l:c -> m:c -> r:c
    l:d -> m:d -> r:d
    l:e -> m:e -> r:e
    l:f -> m:f -> r:f
    l:g -> m:g -> r:g
}
....

. @Id `org.springframework.data.annotation.Id` 
. @DBRef `org.springframework.data.mongodb.core.mapping.DBRef`


==== ProductImage

.ProductImage.java
[source,java]
----
@Getter
@Setter
@Document
public class Product {

  @Id
  private String id;
  private String title;
  private List<String> tags;
  @DBRef
  private List<ProductImage> images;
  private Date createdAt;
  private Date updatedAt;
}
----

=== Repository

